cmake_minimum_required(VERSION 4.2)
project(veriyapilari_proje)

set(CMAKE_CXX_STANDARD 20)

add_executable(veriyapilari_proje
        main.c
        data_structures.c
        data_structures.h
        dom_parser.c
        dom_parser.h
)

add_executable(veriyapilari_proje
        main.c
        data_structures.c
        dom_parser.c
        hash_table.c
        hash_table.c)
